Tarea 2
profedotc/alberto_torrejon pull request #2
Opened 2019-05-25 22:04 UTC by albtorval

Archivos desacoplados y modificación lectura de los mundos con un bucle ifelse. También se han añadido los archivos makefile y gitignore.

2019-05-28 18:21 UTC, profedotc reviewed
Este commit no está bien porque "rompe" tu repositorio. Solamente con el código que hay en tu repositorio en este commit, no se puede compilar nada. Has borrado todo tu código del `main.c`, has hecho un `#include "Gol.h"`, pero no has creado ni `Gol.c` ni `Gol.h`. Todos estos cambios deben estar en un mismo commit para no romper el repositorio. Cualquier commit de tu repositorio debería compilar.

2019-05-28 18:21 UTC, profedotc reviewed
jajja Un poquito exagerado ¿no?

2019-05-28 18:26 UTC, profedotc commented on Makefile
> +	gcc main.o GoL.o -o Exe && ./Exe
Deja esto si quieres, pero no es habitual que el sistema de compilación te ejecute el programa nada más terminar.

2019-05-28 18:26 UTC, profedotc commented on Makefile
> +main.o: main.c
`main.o` depende de `Gol.h`. En `Gol.h` tenemos definidas las macros que determinan el tamaño de nuestro mundo, por ejemplo. Si cambiamos estas macros, deberíamos recompilar el `main.o`

2019-05-28 18:26 UTC, profedotc commented on Makefile
> +GoL.o: GoL.c
Lo mismo para `Gol.o`, también depende de `Gol.h`

2019-05-28 18:26 UTC, profedotc commented on Makefile
> +﻿.PHONY: all ejecutar
El objetivo `clean` también lo puedes añadir aquí

2019-05-28 18:41 UTC, profedotc requested changes

2019-05-28 18:41 UTC, profedotc commented on GoL.c
> +}
Hummm... Aquí hay mucho código repedito, eso no suele ser algo bueno. Quizás deberías optar por la solución del vector de mundos:
```c
for (i=0; i<=X; i++)
	for (j=0; j<=Y; j++)
		mundo[a%2][i][j] = gol_rule(mundo2,i,j);
```

BTW! ¿`i<=X`? Creo que debería ser `i < X`.

2019-05-29 01:12 UTC, albtorval commented
Perdón por tantos commits separados, pero entendí que cada modificación sería un commit. En adelante los comprimiré. Errores arreglados, si no hay ninguna más tengo la tarea 3 también preparada para otro pr.

2019-06-02 18:22 UTC, profedotc commented on GoL.c
> +				world[k][i][j] = 0;
Aquí no debes llegar a `X` ni `X`, `world[k][X][Y]` está accediendo fuera del array. Debes recorrer hasta `X-1` y `Y-1`:
```c
....
for (int i = 0; i < X; i++)
    for (int j = 0; j < Y; j++)
        world[k][i][j];
....
```

2019-06-02 18:22 UTC, profedotc commented on main.c
> +		gol_step(world,i%2);
Aquí hay un problema con el operador módulo y los límites de un entero. Si incrementas `i` indefinidamente, llegará un momento en que no quepan más números en esos 4 bytes, **desbordará** que se dice y empezará a ser negativo. Puedes probar qué pasa cuando haces lo siguiente:
1. `#include <limits.h>`
2. Inicializas `i` a casi su límite: `int i = INT_MAX-5;`
3. Iteras 5 veces.

Puedes solucionarlo de dos formas:
1. Creándote otra variable aparte de `i` y negándola en cada iteración, para que vaya alternando entre 0 y 1: `current_world = !current_world;`
2. Definiendo la variable `i` como _sin-signo_: `unsigned int i = 0;`

2019-06-02 18:23 UTC, profedotc commented
Hago merge. Pero no olvides arreglar esos dos pequeños bugs que tienes.

2019-06-02 18:23 UTC, merged