Tarea 4
profedotc/alberto_torrejon pull request #4
Opened 2019-06-10 17:41 UTC by albtorval

Implementación tarea 4

2019-06-15 18:00 UTC, profedotc requested changes
No compila. Te has hecho un lío al cambiar los nombres de los archivos.

2019-06-15 18:00 UTC, profedotc commented on GoL.c
> +	w->worlds[0] = aux;
Ya que has creado las macros `NEXT` y `CURRENT`, podrías usarlas aquí

2019-06-15 18:00 UTC, profedotc commented on GoL.h
> +    bool **worlds[2];
El tamaño forma parte del estado de tu objeto `world`, por lo que debes incluirlo en la estructura.
Una vez que lo tengas así, no hace falta que pases el tamaño a todas los métodos de tu objeto.

2019-06-15 18:00 UTC, profedotc commented on main.c
> +	gol_alloc(&w,X,Y);
En el main sólo tendría que haber cambiado esta línea.

2019-06-17 09:41 UTC, albtorval commented
Hola Carlos, he arreglado los el desliz de los nombres, pero no sé por qué se ha creado un nuevo PR con el commit nuevo, es decir, tengo abierto dos PR. En este he arreglado lo de las macros pero no he modificado el comentario que me has puesto del tamaño de los mundos porque a partir de la tarea 5 ya si que lo puse como me pides aquí (tengo hasta la 9), si me lo permites cuando me hagas el merge saldrá corregida en la 5. Sorry por el desliz.

2019-06-18 20:21 UTC, profedotc commented
> Hola Carlos, he arreglado los el desliz de los nombres, pero no sé por qué se ha creado un nuevo PR con el commit nuevo, es decir, tengo abierto dos PR. En este he arreglado lo de las macros pero no he modificado el comentario que me has puesto del tamaño de los mundos porque a partir de la tarea 5 ya si que lo puse como me pides aquí (tengo hasta la 9), si me lo permites cuando me hagas el merge saldrá corregida en la 5. Sorry por el desliz.

No problem, pero sigue sin funcionar, te comento en Patch-1.

2019-06-20 15:37 UTC, albtorval commented
Creo que ahora debería de estar

2019-06-25 19:15 UTC, merged